baseURL = "/"
title = "PCOS With Science: Understanding Polycystic Ovary Syndrome"
theme = "hugo-bearblog"

[params]
  description = "Comprehensive information about Polycystic Ovary Syndrome (PCOS), its symptoms, diagnosis, and management. By Science."
  favicon = "favicon.ico"
  logo = "img/logo.png"

[menu]
  [[menu.main]]
    identifier = "diagnosis"
    name = "Diagnosis"
    url = "/diagnosis"
    weight = 2
  [[menu.main]]
    identifier = "treatment"
    name = "Treatment"
    url = "/treatment"
    weight = 3
  [[menu.main]]
    identifier = "lifestyle"
    name = "Lifestyle"
    url = "/lifestyle"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true
